// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqqdrurhjudssbaixukg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xcWRydXJoanVkc3NiYWl4dWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzU4OTEsImV4cCI6MjA2Nzc1MTg5MX0.loRA6gdlofArspMFdnz6h5EemZrLL3cz1FddjstSmJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});